<?php
// vim: set expandtab tabstop=4 shiftwidth=4 autoindent smartindent:
//---------------------------------------------------------
// CAPTAIN  SLOG
//---------------------------------------------------------
//
//	FILE:       prepare.inc
//	SYSTEM:     New tools
//	AUTHOR:     Mark Addinall
//	DATE:       22/03/2013
//	SYNOPSIS:  
//  A stub that dummies the DB2 library requirement.
//



?>


